### PR TITLE
build!: v2 rho prepare

### PR DESCRIPTION
**Pull request by dongsam**
## Description

- bump cosmos-sdk to v0.46.x ( currently v0.46.0 )
- remove swap functionality ( circuit breaker enabled and deprecated on cosmos-hub )
- bump package name to liquididty/v2

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by dongsam** [comment]
> Hi @dongsam, can you please bump to sdk 0.46-rc1 ? we need this for rho, Thank you!

Hi @yaruwangway, I just released [v2.0.0-rc1](https://github.com/Gravity-Devs/liquidity/releases/tag/v2.0.0-rc1) which is based sdk 0.46.0-rc1

**Review by hallazzang — APPROVED** [review]
Generally looking good for me

**Review by kogisin — APPROVED** [review]

**Comment by dongsam** [comment]
First of all, we released [v2.0.0-rc3](https://github.com/Gravity-Devs/liquidity/releases/tag/v2.0.0-rc3) based on the PR branch. We will release official v2.0.0 after confirming that there is no conflict or issue with other modules in the Rho upgrade PR

**Comment by dongsam** [comment]
https://github.com/Gravity-Devs/liquidity/releases/tag/v2.0.0
final v2.0.0 released, which is using cosmos-sdk v0.46.0

**Pull request merged**
